// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFUq__pPKv4F4REzBIeuCuon1orHX4W1I',
    appId: '1:911749206594:web:56449a0bd77495d1ae93db',
    messagingSenderId: '911749206594',
    projectId: 'tubes-mobile-fcc9c',
    authDomain: 'tubes-mobile-fcc9c.firebaseapp.com',
    storageBucket: 'tubes-mobile-fcc9c.appspot.com',
    measurementId: 'G-DWTVL87C7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKIpwTRwgihVZDWKqTqvcLZ1-zWiOkVM',
    appId: '1:911749206594:android:90666c54b2c31890ae93db',
    messagingSenderId: '911749206594',
    projectId: 'tubes-mobile-fcc9c',
    storageBucket: 'tubes-mobile-fcc9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpwcGmqpR8LFDnPBAMCm4T_js-hO8ars',
    appId: '1:911749206594:ios:3bb0f41167547427ae93db',
    messagingSenderId: '911749206594',
    projectId: 'tubes-mobile-fcc9c',
    storageBucket: 'tubes-mobile-fcc9c.appspot.com',
    iosClientId: '911749206594-94sjvbdvec2prr1u6hhr3p3j4bdjji4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesMobile',
  );
}
